sudo: required
services:
  - docker
before_install:
- docker build -t 315426346/travis-ci:latest -f Dockerfile.dev  .
script:
  - docker run -e CI=true 315426346/travis-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  access_key_id: $access_key_id
  secret_access_key: "$secret_access_key"
  app: "react"
  env: "React-env"
  bucket_name: "elasticbeanstalk-us-east-1-995604946987"
  bucket_path: "react"
  dockerfile: Dockerfile

  on:
    branch: main


