sudo: required
services:
  - docker
before_install:
- docker build -t 315426346/travis-ci:latest -f Dockerfile.dev  .
script:
  - docker run -e CI=true 315426346/travis-ci npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $aws_access_key
  secret_access_key: $aws_secret
  region: "us-east-1"
  env: "React-env"
  app: "react"
  bucket_name: "elasticbeanstalk-us-east-1-995604946987"
  bucket_path: "react"
  on:
    branch: main