version: "3"
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
    volumes:
      - .:/usr/app
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
